// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANw22zCMjLcXjHYDJFh5_6TC-LJqoHjxw',
    appId: '1:268435899001:web:21455c8e8cf0963fb2caa8',
    messagingSenderId: '268435899001',
    projectId: 'keepnotes-59137',
    authDomain: 'keepnotes-59137.firebaseapp.com',
    storageBucket: 'keepnotes-59137.appspot.com',
    measurementId: 'G-ERBDH6K3S9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZPqe3AOt4y98L12x9DNDlGULajplbry0',
    appId: '1:268435899001:android:2315e1de53d845c8b2caa8',
    messagingSenderId: '268435899001',
    projectId: 'keepnotes-59137',
    storageBucket: 'keepnotes-59137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLofad-g9Ic5cl5fRX5lJS9lSNcuNcEgM',
    appId: '1:268435899001:ios:4de51ae20161ed06b2caa8',
    messagingSenderId: '268435899001',
    projectId: 'keepnotes-59137',
    storageBucket: 'keepnotes-59137.appspot.com',
    iosBundleId: 'com.keepnotebooks.app.keepnotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLofad-g9Ic5cl5fRX5lJS9lSNcuNcEgM',
    appId: '1:268435899001:ios:4de51ae20161ed06b2caa8',
    messagingSenderId: '268435899001',
    projectId: 'keepnotes-59137',
    storageBucket: 'keepnotes-59137.appspot.com',
    iosBundleId: 'com.keepnotebooks.app.keepnotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANw22zCMjLcXjHYDJFh5_6TC-LJqoHjxw',
    appId: '1:268435899001:web:e084e2b6f3ba2497b2caa8',
    messagingSenderId: '268435899001',
    projectId: 'keepnotes-59137',
    authDomain: 'keepnotes-59137.firebaseapp.com',
    storageBucket: 'keepnotes-59137.appspot.com',
    measurementId: 'G-8TXWLVQQY4',
  );
}